# Generated by Django 4.0.4 on 2022-05-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='diner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diner_menus', to='delivery.diner'),
        ),
        migrations.CreateModel(
            name='MenuOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mandatory', models.BooleanField(default=False)),
                ('select_min', models.IntegerField(default=0)),
                ('select_max', models.IntegerField(default=1)),
                ('for_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_group', to='delivery.menu')),
            ],
        ),
    ]
