# Generated by Django 4.0.4 on 2022-05-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_menu_diner_menuoptiongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category_diners', models.ManyToManyField(related_name='diner_categories', to='delivery.diner')),
            ],
        ),
    ]
