# Generated by Django 4.0.4 on 2022-05-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default=1000)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_fee', to='delivery.area')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_area', to='delivery.diner')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='diners',
            field=models.ManyToManyField(related_name='deliver_area', through='delivery.DeliveryArea', to='delivery.diner'),
        ),
    ]
