# Generated by Django 4.0.4 on 2022-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_area_deliveryarea_area_diners'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
