# Generated by Django 4.0.4 on 2022-05-16 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_area_latitude_area_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='closes',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='diner',
            name='opens',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
